SET TAG_VERSION="0.6.3"

IF "%APPVEYOR_REPO_BRANCH%" == "dev" GOTO DEV

:DEV
git tag -a %TAG_VERSION%.%APPVEYOR_BUILD_NUMBER% -m "%APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED%"
git push origin --tags

IF "%APPVEYOR_REPO_BRANCH%" == "pre-release" GOTO RELEASE
IF "%APPVEYOR_REPO_BRANCH%" == "release" GOTO RELEASE

:RELEASE
git tag -a %TAG_VERSION% -m "%APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED%"
git push origin --tags