SET TAG_VERSION="v0.6.3"

IF "%APPVEYOR_REPO_BRANCH%" == "dev" git tag -a %TAG_VERSION%.%APPVEYOR_BUILD_NUMBER% -m "%APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED%"

IF "%APPVEYOR_REPO_BRANCH%" == "pre-release" git tag -a %TAG_VERSION% -m "%APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED%"
IF "%APPVEYOR_REPO_BRANCH%" == "release" git tag -a %TAG_VERSION% -m "%APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED%"

git push origin --tags